# To change the effect of the smoothing change the image and filter values

net:
    model_file: 'models/opencv_face_detector_uint8.pb'
    cfg_file: 'models/opencv_face_detector.pbtxt'
    
    conf_threshold: 0.6

image:
    # hsv range affects the skin region to be selected for filtering
    hsv_low: !!python/tuple [0.,80.,80.]
    hsv_high: !!python/tuple [200.,255.,255.]

    # BlobFromImage settings
    mean: [104, 117, 123]
    size: !!python/tuple [200, 200]

    # Output image filenames
    output: 'output_'
    output_steps: 'combined_'

    bbox_color: !!python/tuple [255, 204, 102]

    img_steps_height: 300

video:
    output: 'video_output_'
    fps: 30

filter:
    # Diameter of each pixel neighborhood
    diameter: 15

    # Value of sigma in the color space. The greater the value, the colors farther to each other will start to get mixed.
    sigma_1: 50 
    sigma_2: 50